default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: <%= ENV.fetch("DB_USER") { `id -un` } %>
  password: <%= ENV.fetch("DB_PASS") { '' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

development:
  <<: *default
  database: hivecolor_development

test:
  <<: *default
  database: hivecolor_test

production:
  <<: *default
  database: hivecolor_production